version: "3.6"

services:
  shoutcast:
    build: ./
    ports:
      - 8000:8000
    volumes:
      - "/tmp/var/folders/cg/_6hd71p14jb8rym25wmd0dnr0000gq/T/tmp.1XqH7dpC:/run"
      - "./logs:/var/log"
      - "./playlist:/usr/local/shoutcast/sc_trans/music"
      - "./sc_serv.conf:/usr/local/shoutcast/sc_serv.conf"
      - "./sc_trans_basic.conf:/usr/local/shoutcast/sc_trans/sc_trans_basic.conf"
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
    environment:
      - LOGTARGET_HOST: '127.0.0.1'
      - LOGTARGET_POST: '60000'
    cap_add:
      - ALL
    privileged: true